export const GET_LAYER_HISTORY_FROM_API = "GET_LAYER_HISTORY_FROM_API";
export const SET_LAYER_HISTORY = "SET_LAYER_HISTORY";

export const UPDATE_LAYER = "UPDATE_LAYER";

export const UNDO = "UNDO";
export const REDO = "REDO";

export const UPDATE_LAYER_TO_API = "UPDATE_LAYER_TO_API";
export const UPDATE_FEATURES = "UPDATE_FEATURES";