export const GET_LAYER_HISTORY_FROM_API = "GET_LAYER_HISTORY_FROM_API";
export const SET_LAYER_HISTORY = "SET_LAYER_HISTORY";

export const UNDO_LAYER_TO_LOCAL_STORAGE = "UNDO_LAYER_TO_LOCAL_STORAGE";
export const UNDO = "UNDO";
export const REDO = "REDO";

export const UPDATE_LAYER_TO_API = "UPDATE_LAYER_TO_API";
export const UPDATE_FEATURES = "UPDATE_FEATURES";

export const DELETE_FEATURES_FROM_LAYER_STORAGE = "DELETE_FEATURES_FROM_LAYER_STORAGE";
export const DELETE_FEATURES = "DELETE_FEATURES";